### ISSUE TITLE
Display typing test sample text

### ISSUE THREAD

**Issue by AnishAzharudeen** [AnishAzharudeen/CodingForEveryone#7]
**User story**

As a user, I want to see a sample of text to type so that I know what I need to type to measure my speed.

**Acceptance Criteria:**

- [ ] A sentence of sample text is clearly visible and formatted for easy reading.
- [ ] The sample text is randomly chosen from a set selection for each level of difficulty. (easy, medium or hard)

**Tasks:**

- [ ] Implement functionality to display a random paragraph of text upon starting the test, depending on the level of difficulty selected by the user.
- [ ] Ensure the text is clearly visible and formatted for easy reading.
