### ISSUE TITLE
Calculate and display Words Per Minute (WPM)

### ISSUE THREAD

**Issue by AnishAzharudeen** [AnishAzharudeen/CodingForEveryone#9]
As a user, I want to see my typing speed calculated in Words Per Minute (WPM) when I finish typing so that I know my typing performance.

**Acceptance Criteria:**

- [ ] WPM is calculated based on the number of correctly typed words and elapsed time.
- [ ] The difficulty level and WPM result is displayed immediately after completing the test.

**Tasks:**

- [ ] Create a results area to display the level, time and Words Per Minute (WPM) results to the user
- [ ] Implement functionality to calculate the number of correctly typed WPM.
- [ ] Display the WPM result with the level and time immediately after the user completes the test.
